In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [47]:
data = pd.read_excel(r'C:\Users\nijat\Desktop\PYTHON - KURS\Ders 21\user_knowledge_clf.xls')
data.head(5)

STG   SCG   STR   LPR   PEG       UNS
0  0.00  0.00  0.00  0.00  0.00  very_low
1  0.08  0.08  0.10  0.24  0.90      High
2  0.06  0.06  0.05  0.25  0.33       Low
3  0.10  0.10  0.15  0.65  0.30    Middle
4  0.08  0.08  0.08  0.98  0.24       Low

In [48]:
data.describe(include='all')

STG         SCG         STR         LPR         PEG  UNS
count   403.000000  403.000000  403.000000  403.000000  403.000000  403
unique         NaN         NaN         NaN         NaN         NaN    5
top            NaN         NaN         NaN         NaN         NaN  Low
freq           NaN         NaN         NaN         NaN         NaN  129
mean      0.353141    0.355940    0.457655    0.431342    0.456360  NaN
std       0.212018    0.215531    0.246684    0.257545    0.266775  NaN
min       0.000000    0.000000    0.000000    0.000000    0.000000  NaN
25%       0.200000    0.200000    0.265000    0.250000    0.250000  NaN
50%       0.300000    0.300000    0.440000    0.330000    0.400000  NaN
75%       0.480000    0.510000    0.680000    0.650000    0.660000  NaN
max       0.990000    0.900000    0.950000    0.990000    0.990000  NaN

In [49]:
data.isnull().sum()

STG    0
SCG    0
STR    0
LPR    0
PEG    0
UNS    0
dtype: int64

In [50]:
data.corr()

STG       SCG       STR       LPR       PEG
STG  1.000000  0.049023 -0.051889  0.113957  0.198629
SCG  0.049023  1.000000  0.121235  0.119716  0.193566
STR -0.051889  0.121235  1.000000  0.083423  0.148338
LPR  0.113957  0.119716  0.083423  1.000000 -0.039283
PEG  0.198629  0.193566  0.148338 -0.039283  1.000000

In [51]:
data['UNS'].value_counts()

Low         129
Middle      122
High        102
Very Low     26
very_low     24
Name: UNS, dtype: int64

In [52]:
data['UNS'] = np.where(data['UNS'] == 'very_low', 'Very Low', data['UNS'])

In [53]:
data['UNS'].value_counts()

Low         129
Middle      122
High        102
Very Low     50
Name: UNS, dtype: int64

In [54]:
data['UNS'] = np.where(data['UNS'] == 'Very Low', '0', data['UNS'])

In [55]:
data['UNS'] = np.where(data['UNS'] == 'Low', '1', data['UNS'])

In [56]:
data['UNS'] = np.where(data['UNS'] == 'Middle', '2', data['UNS'])

In [57]:
data['UNS'] = np.where(data['UNS'] == 'High', '3', data['UNS'])

In [58]:
data['UNS'].value_counts()

1    129
2    122
3    102
0     50
Name: UNS, dtype: int64

In [59]:
data.head()

STG   SCG   STR   LPR   PEG UNS
0  0.00  0.00  0.00  0.00  0.00   0
1  0.08  0.08  0.10  0.24  0.90   3
2  0.06  0.06  0.05  0.25  0.33   1
3  0.10  0.10  0.15  0.65  0.30   2
4  0.08  0.08  0.08  0.98  0.24   1

In [61]:
data.columns

Index(['STG', 'SCG', 'STR', 'LPR', 'PEG', 'UNS'], dtype='object')

In [68]:
targets = data[['UNS']]

inputs = data[['STG', 'SCG', 'STR', 'LPR', 'PEG']]

In [69]:
targets

UNS
0     0
1     3
2     1
3     2
4     1
..   ..
398   3
399   3
400   1
401   2
402   2

[403 rows x 1 columns]

In [70]:
targets.value_counts()

UNS
1      129
2      122
3      102
0       50
dtype: int64

In [71]:
inputs

STG   SCG   STR   LPR   PEG
0    0.00  0.00  0.00  0.00  0.00
1    0.08  0.08  0.10  0.24  0.90
2    0.06  0.06  0.05  0.25  0.33
3    0.10  0.10  0.15  0.65  0.30
4    0.08  0.08  0.08  0.98  0.24
..    ...   ...   ...   ...   ...
398  0.90  0.78  0.62  0.32  0.89
399  0.85  0.82  0.66  0.83  0.83
400  0.56  0.60  0.77  0.13  0.32
401  0.66  0.68  0.81  0.57  0.57
402  0.68  0.64  0.79  0.97  0.24

[403 rows x 5 columns]

In [72]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.3, random_state=42)

In [73]:
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import roc_auc_score
import seaborn as sns
sns.set()

In [78]:
def evaluate(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)*100
    cm = confusion_matrix(y_test, y_pred)
    print('Model Performance')
    print('Accuracy is', accuracy)
    print('CM', cm)
    return accuracy
    return cm

In [79]:
base_model = svm.SVC()
base_model.fit(X_train, y_train)
base_accuracy = evaluate(base_model, X_test, y_test)

Model Performance
Accuracy is 90.9090909090909
CM [[12  6  0  0]
 [ 0 36  0  0]
 [ 0  3 36  1]
 [ 0  0  1 26]]


D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [80]:
from sklearn.model_selection import RandomizedSearchCV

kernel = ['poly', 'rbf', 'sigmoid']
# kernel trick

gamma = ['scale', 'auto'] 
#Kernel coefficient for ‘rbf’, ‘poly’ and ‘sigmoid’.

#if gamma='scale' (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma
#if ‘auto’, uses 1 / n_features.

C = [1, 10, 100, 1e3, 1e4, 1e5, 1e6]
# Must be strictly positive.

#epsilon = [0.1 , 0.01, 0.001, 0.0001]


# Create the random grid
random_grid = {'kernel': kernel,
               'gamma': gamma,
               'C': C}
print(random_grid)

{'kernel': ['poly', 'rbf', 'sigmoid'], 'gamma': ['scale', 'auto'], 'C': [1, 10, 100, 1000.0, 10000.0, 100000.0, 1000000.0]}


In [81]:
svc_random = RandomizedSearchCV(estimator = base_model, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=1, n_jobs = -1)
# Fit the random search model
svc_random.fit(X_train, y_train)

D:\ANACONDA\lib\site-packages\sklearn\model_selection\_search.py:292: UserWarning: The total space of parameters 42 is smaller than n_iter=100. Running 42 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Fitting 3 folds for each of 42 candidates, totalling 126 fits


D:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=100, n_jobs=-1,
                   param_distributions={'C': [1, 10, 100, 1000.0, 10000.0,
                                              100000.0, 1000000.0],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['poly', 'rbf', 'sigmoid']},
                   verbose=1)

In [82]:
svc_random.best_params_

{'kernel': 'rbf', 'gamma': 'auto', 'C': 100}

In [83]:
optimized_model = svc_random.best_estimator_
optmized_accuracy = evaluate(optimized_model, X_test, y_test)

Model Performance
Accuracy is 94.21487603305785
CM [[15  3  0  0]
 [ 0 36  0  0]
 [ 0  3 37  0]
 [ 0  0  1 26]]
