# NumPy bölməsi üçün tapşırıqlar


#### NumPy kitabxanasını daxil edin

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

#### 10 dənə 0-dan təşkil olunmuş array yaradin. (Nəticə aşağıda göstərilən kimi olmalıdır)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 10 dənə 1-dən təşkil olunmuş array yaradin.

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 10 dənə 5-dən təşkil olunmuş array yaradin.

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 10-dan  50-ə kimi  yalnız cüt integer ədədlərdən təşkil olunmuş array yaradın

In [7]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

####  0-dan 8-ə kimi ədədlərdən təşkil olunmuş 3 sətir və 3 sütündan təşkil olunmuş matrix qurun

In [8]:
a = np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 3 sətir və 3 sütündan təşkil olunmuş identity matrix qurun

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  NumPy kitabxanası ilə 0 və 1 arasında yerləşən random ədəd yaradın (Nəticə random olduğu üçün sizin nəticəniz fərqli ədəd alına bilər)

In [11]:
np.random.rand(1)

array([0.78899684])

#### 25 təsadüfi ədəddən ibarət array yaratmaq üçün NumPy istifadə edin

In [12]:
np.linspace(0, 1, 100).round(2)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Aşağıdakı matrisi yaradın:

## Indexing və Selection

Verilmiş matris nəticələrini təkrarlayın

In [13]:
import numpy as np

matrix = np.arange(1,21).reshape(4,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
# Aşağıdakı 2 sətir 4 sütundan təşkil olunmuş matriksi nəticə olaraq görmək üçün kodu yazın

In [15]:
a = matrix[2:, 1:5]
a

array([[12, 13, 14, 15],
       [17, 18, 19, 20]])

In [16]:
# Matriksin daxilindən 14 dəyərin slicing yolu ilə chixarın

In [17]:
matrix = np.arange(1,21).reshape(4,5)
matrix

a2 = matrix[2:3, 3:4]
a2

array([[14]])

In [18]:
# Aşağıdakı sütunu nəticə olaraq görmək üçün kodu yazın

In [19]:
matrix = np.arange(1,21).reshape(4,5)
matrix

a3 = matrix[0:3, 1:2]
a3

array([[ 2],
       [ 7],
       [12]])

In [20]:
# Aşağıdakı sətiri nəticə olaraq görmək üçün kodu yazın

In [21]:
matrix = np.arange(1,21).reshape(4,5)
matrix

a4 = matrix[3:]
a4

array([[16, 17, 18, 19, 20]])

In [22]:
# Aşağıdakı 2 sətir 5 sütundan təşkil olunmuş matriksi nəticə olaraq görmək üçün kodu yazın

In [23]:
matrix = np.arange(1,21).reshape(4,5)
matrix

a5 = matrix[2:]
a5

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Matriks daxilindəki dəyərlərin cəmin hesablayın

In [24]:
matrix.sum()

210

#### Hər bir sütunun dəyərlərinin cəmin hesablayın

In [25]:
matrix = np.arange(1,21).reshape(4,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
matrix.sum(0)

array([34, 38, 42, 46, 50])

a vektoru yaradib 1den 10a kimi reqemlerle doldurun.

b vektorunda eger reqemler 5den kichikdirse, eyni reqemler yazilsin eks halda 5den boyuk reqemler 10a vurulsun. 

a ve b vektorlarin print edin.

In [27]:
a = np.arange(0,10)
print(a)

b = np.where(a < 5, a, a*10)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


### Pandas kitabxanasin daxil edin

In [28]:
import pandas as pd

Dictionary vasiesile ashaqidaki data-ni yaradin

In [29]:
df = pd.DataFrame({
    'State': ['NY', 'TX', 'FL', 'NY', 'FL', 'NY', np.nan],
    'Food': ['steak', 'lamb', np.nan, 'french fries', 'steak', 'steak', 'lamb'],
    'Age': [30, np.nan, 18, 32, np.nan, 25, 28],
    'Height': [165, 180, np.nan, np.nan, 172, 185, 175],
    'Score': [4.6, 8.3, 9.3, 3.3, 1.8, 5.5, 7.4]
}, index='Jane Niko Aaron Penelope Dean Christina Cornelia'.split())


df

State          Food   Age  Height  Score
Jane         NY         steak  30.0   165.0    4.6
Niko         TX          lamb   NaN   180.0    8.3
Aaron        FL           NaN  18.0     NaN    9.3
Penelope     NY  french fries  32.0     NaN    3.3
Dean         FL         steak   NaN   172.0    1.8
Christina    NY         steak  25.0   185.0    5.5
Cornelia    NaN          lamb  28.0   175.0    7.4

Data-da gorulduyu kimi missing value-lar var, onlari evez edin.

1. State sutunundaki bosluqu en chox tekrarlanan sheher ile evez edin
2. Food sutunundaki bosluqu en chox tekrarlanan yemek ile evez edin
3. Age sutunundaki bosluqlari orta eded ile evez edin
4. Height sutunundaki bosluqlari 80 faizlik quantile ile evez edin

Neticede ashaqidaki kimi data alinacaq.

In [30]:
df.describe(include= 'all')

State   Food        Age      Height     Score
count      6      6   5.000000    5.000000  7.000000
unique     3      3        NaN         NaN       NaN
top       NY  steak        NaN         NaN       NaN
freq       3      3        NaN         NaN       NaN
mean     NaN    NaN  26.600000  175.400000  5.742857
std      NaN    NaN   5.458938    7.635444  2.733043
min      NaN    NaN  18.000000  165.000000  1.800000
25%      NaN    NaN  25.000000  172.000000  3.950000
50%      NaN    NaN  28.000000  175.000000  5.500000
75%      NaN    NaN  30.000000  180.000000  7.850000
max      NaN    NaN  32.000000  185.000000  9.300000

In [31]:
df['State'] = df['State'].fillna(df['State'].mode()[0])

df

State          Food   Age  Height  Score
Jane         NY         steak  30.0   165.0    4.6
Niko         TX          lamb   NaN   180.0    8.3
Aaron        FL           NaN  18.0     NaN    9.3
Penelope     NY  french fries  32.0     NaN    3.3
Dean         FL         steak   NaN   172.0    1.8
Christina    NY         steak  25.0   185.0    5.5
Cornelia     NY          lamb  28.0   175.0    7.4

In [32]:
df['Food'] = df['Food'].fillna(df['Food'].mode()[0])
df

State          Food   Age  Height  Score
Jane         NY         steak  30.0   165.0    4.6
Niko         TX          lamb   NaN   180.0    8.3
Aaron        FL         steak  18.0     NaN    9.3
Penelope     NY  french fries  32.0     NaN    3.3
Dean         FL         steak   NaN   172.0    1.8
Christina    NY         steak  25.0   185.0    5.5
Cornelia     NY          lamb  28.0   175.0    7.4

In [33]:
df['Age'].fillna(value=df['Age'].mean(), inplace=True)
df

State          Food   Age  Height  Score
Jane         NY         steak  30.0   165.0    4.6
Niko         TX          lamb  26.6   180.0    8.3
Aaron        FL         steak  18.0     NaN    9.3
Penelope     NY  french fries  32.0     NaN    3.3
Dean         FL         steak  26.6   172.0    1.8
Christina    NY         steak  25.0   185.0    5.5
Cornelia     NY          lamb  28.0   175.0    7.4

In [34]:
df['Height'] = df['Height'].fillna(value=df['Height'].quantile(0.8))
df

State          Food   Age  Height  Score
Jane         NY         steak  30.0   165.0    4.6
Niko         TX          lamb  26.6   180.0    8.3
Aaron        FL         steak  18.0   181.0    9.3
Penelope     NY  french fries  32.0   181.0    3.3
Dean         FL         steak  26.6   172.0    1.8
Christina    NY         steak  25.0   185.0    5.5
Cornelia     NY          lamb  28.0   175.0    7.4

Ad-lar olan sutunu index-den chixarin.

In [35]:
df = df.reset_index(level=0)
df

index State          Food   Age  Height  Score
0       Jane    NY         steak  30.0   165.0    4.6
1       Niko    TX          lamb  26.6   180.0    8.3
2      Aaron    FL         steak  18.0   181.0    9.3
3   Penelope    NY  french fries  32.0   181.0    3.3
4       Dean    FL         steak  26.6   172.0    1.8
5  Christina    NY         steak  25.0   185.0    5.5
6   Cornelia    NY          lamb  28.0   175.0    7.4

'Index' sutunun adini 'Names' olaraq deyishdirin

In [36]:
df.rename(columns={'index':'Names'}, inplace=True)

df

Names State          Food   Age  Height  Score
0       Jane    NY         steak  30.0   165.0    4.6
1       Niko    TX          lamb  26.6   180.0    8.3
2      Aaron    FL         steak  18.0   181.0    9.3
3   Penelope    NY  french fries  32.0   181.0    3.3
4       Dean    FL         steak  26.6   172.0    1.8
5  Christina    NY         steak  25.0   185.0    5.5
6   Cornelia    NY          lamb  28.0   175.0    7.4

Ashaqidaki yeni data-ni yaradin

In [37]:
df2 = pd.DataFrame({
    'Names': ['Jane', 'Niko', 'Aaron', 'Penelope', 'Dean', 'Christina', 'Cornelia'],
    'Income': [3000, 1500, 1800, 3200, 2500, 2700, 2200],
    'Weight': [80, 85, 90, 72, 75, 65,70]
}, index='0 1 2 3 4 5 6'.split())


df2

Names  Income  Weight
0       Jane    3000      80
1       Niko    1500      85
2      Aaron    1800      90
3   Penelope    3200      72
4       Dean    2500      75
5  Christina    2700      65
6   Cornelia    2200      70

Her iki data-dan eyni olan sutun uzerinden bu datalari birleshdirin. Neticede ashaqidaki data yaranacaq.

In [38]:
df3 = pd.merge(df, df2, how = 'outer',on = 'Names')
df3

Names State          Food   Age  Height  Score  Income  Weight
0       Jane    NY         steak  30.0   165.0    4.6    3000      80
1       Niko    TX          lamb  26.6   180.0    8.3    1500      85
2      Aaron    FL         steak  18.0   181.0    9.3    1800      90
3   Penelope    NY  french fries  32.0   181.0    3.3    3200      72
4       Dean    FL         steak  26.6   172.0    1.8    2500      75
5  Christina    NY         steak  25.0   185.0    5.5    2700      65
6   Cornelia    NY          lamb  28.0   175.0    7.4    2200      70

Datanin descriptive statistikasina baxin(hemn numeric hem de categoric deyerler uzre)

In [39]:
df3.describe(include='all')

Names State   Food        Age      Height     Score       Income  \
count      7     7      7   7.000000    7.000000  7.000000     7.000000   
unique     7     3      3        NaN         NaN       NaN          NaN   
top     Jane    NY  steak        NaN         NaN       NaN          NaN   
freq       1     4      4        NaN         NaN       NaN          NaN   
mean     NaN   NaN    NaN  26.600000  177.000000  5.742857  2414.285714   
std      NaN   NaN    NaN   4.457204    6.806859  2.733043   620.291790   
min      NaN   NaN    NaN  18.000000  165.000000  1.800000  1500.000000   
25%      NaN   NaN    NaN  25.800000  173.500000  3.950000  2000.000000   
50%      NaN   NaN    NaN  26.600000  180.000000  5.500000  2500.000000   
75%      NaN   NaN    NaN  29.000000  181.000000  7.850000  2850.000000   
max      NaN   NaN    NaN  32.000000  185.000000  9.300000  3200.000000   

           Weight  
count    7.000000  
unique        NaN  
top           NaN  
freq          NaN  
mean    76.714286  
std      8.788521  
min     65.000000  
25%     71.000000  
50%     75.000000  
75%     82.500000  
max     90.000000

Group by istifade ederek mueyyen edin ki, her State uzre insanlarin weight ve height emsallarin orta ededi ne qederdir.


In [40]:
by_comp = df3.groupby("State")

by_comp.mean()

Age  Height  Score  Income  Weight
State                                      
FL     22.30   176.5   5.55  2150.0   82.50
NY     28.75   176.5   5.20  2775.0   71.75
TX     26.60   180.0   8.30  1500.0   85.00

Insanlarin yashlarina gore orta gelirleri ne qederdir?

In [41]:
by_comp = df3.groupby("Age")

by_comp.mean()

Height  Score  Income  Weight
Age                                
18.0   181.0   9.30  1800.0    90.0
25.0   185.0   5.50  2700.0    65.0
26.6   176.0   5.05  2000.0    80.0
28.0   175.0   7.40  2200.0    70.0
30.0   165.0   4.60  3000.0    80.0
32.0   181.0   3.30  3200.0    72.0

Income_status adli sutun yaradin. 2000 dollardan yuxari alanlar uchun 'high' qeyd olunsun, az alanlar uchun 'low' qeyd olunsun

In [42]:

df3["income_status"] = np.where(df3.Income > 2000, 'high', 'low')

df3

Names State          Food   Age  Height  Score  Income  Weight  \
0       Jane    NY         steak  30.0   165.0    4.6    3000      80   
1       Niko    TX          lamb  26.6   180.0    8.3    1500      85   
2      Aaron    FL         steak  18.0   181.0    9.3    1800      90   
3   Penelope    NY  french fries  32.0   181.0    3.3    3200      72   
4       Dean    FL         steak  26.6   172.0    1.8    2500      75   
5  Christina    NY         steak  25.0   185.0    5.5    2700      65   
6   Cornelia    NY          lamb  28.0   175.0    7.4    2200      70   

  income_status  
0          high  
1           low  
2           low  
3          high  
4          high  
5          high  
6          high

In [43]:
df3

Names State          Food   Age  Height  Score  Income  Weight  \
0       Jane    NY         steak  30.0   165.0    4.6    3000      80   
1       Niko    TX          lamb  26.6   180.0    8.3    1500      85   
2      Aaron    FL         steak  18.0   181.0    9.3    1800      90   
3   Penelope    NY  french fries  32.0   181.0    3.3    3200      72   
4       Dean    FL         steak  26.6   172.0    1.8    2500      75   
5  Christina    NY         steak  25.0   185.0    5.5    2700      65   
6   Cornelia    NY          lamb  28.0   175.0    7.4    2200      70   

  income_status  
0          high  
1           low  
2           low  
3          high  
4          high  
5          high  
6          high

'condition' adli sutun yaradin. 

eger State FL  ve Score 5-den boyuk, State NY ve Score 6-dan boyuk, State TX ve Score 4-den boyuk olarsa o zaman high_score yazilsin.

eks halda low_score yazilsin.

In [44]:
conditions = [
  (df3.State == 'FL') & (df3.Score> 5),
  (df3.State =='NY') & (df3.Score> 6),
    (df3.State == 'TX') & (df3.Score> 4),
    
]
values = ["high_score", 'high_score', 'high_score' ]
df3["condition"] = np.select(conditions, values, default='low_score')
df3

Names State          Food   Age  Height  Score  Income  Weight  \
0       Jane    NY         steak  30.0   165.0    4.6    3000      80   
1       Niko    TX          lamb  26.6   180.0    8.3    1500      85   
2      Aaron    FL         steak  18.0   181.0    9.3    1800      90   
3   Penelope    NY  french fries  32.0   181.0    3.3    3200      72   
4       Dean    FL         steak  26.6   172.0    1.8    2500      75   
5  Christina    NY         steak  25.0   185.0    5.5    2700      65   
6   Cornelia    NY          lamb  28.0   175.0    7.4    2200      70   

  income_status   condition  
0          high   low_score  
1           low  high_score  
2           low  high_score  
3          high   low_score  
4          high   low_score  
5          high   low_score  
6          high  high_score

Data-nin yalniz State NY olub ve geliri 3000den (3000 daxil olmaqla) boyuk olan hissesini chixardin

In [45]:
df3[(df3['State'] == 'NY') & (df3['Income'] >= 3000)]


Names State          Food   Age  Height  Score  Income  Weight  \
0      Jane    NY         steak  30.0   165.0    4.6    3000      80   
3  Penelope    NY  french fries  32.0   181.0    3.3    3200      72   

  income_status  condition  
0          high  low_score  
3          high  low_score